export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const COMPANYSIGNUP_SUCCESS = 'COMPANYSIGNUP_SUCCESS';
export const COMPANYSIGNUP_FAIL = 'COMPANYSIGNUP_FAIL';
export const COMPANYUSER_LOADED = 'COMPANYUSER_LOADED';
export const COMPANYAUTH_ERROR = 'COMPANYAUTH_ERROR';
export const COMPANYSIGNIN_FAIL = 'COMPANYSIGNIN_FAIL';
export const COMPANYSIGNIN_SUCCESS = 'COMPANYSIGNIN_SUCCESS';
export const COMPANY_SIGNOUT = 'COMPANY_SIGNOUT';
export const COMPANY_GETPROFILE = 'COMPANY_GETPROFILE';
export const COMPANY_EDITPROFILE = 'COMPANY_EDITPROFILE';
export const COMPANY_PROFILEERROR = 'COMPANY_PROFILEERROR';
export const COMPANY_GETREVIEWS = 'COMPANY_GETREVIEWS';
export const COMPANY_GETREVIEW = 'COMPANY_GETREVIEW';
export const COMPANY_REVIEWS_ERROR = 'COMPANY_REVIEWS_ERROR';

// Student Authorization
export const STUDENT_SIGNUP_SUCCESS = 'STUDENT_SIGNUP_SUCCESS';
export const STUDENT_SIGNUP_FAIL = 'STUDENT_SIGNUP_FAIL';
export const STUDENT_USER_LOADED = 'STUDENT_USER_LOADED';
export const STUDENT_AUTH_ERROR = 'STUDENT_AUTH_ERROR';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';