export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const COMPANYSIGNUP_SUCCESS = 'COMPANYSIGNUP_SUCCESS';
export const COMPANYSIGNUP_FAIL = 'COMPANYSIGNUP_FAIL';
export const COMPANYUSER_LOADED = 'COMPANYUSER_LOADED';
export const COMPANYAUTH_ERROR = 'COMPANYAUTH_ERROR';
export const COMPANYSIGNIN_FAIL = 'COMPANYSIGNIN_FAIL';
export const COMPANYSIGNIN_SUCCESS = 'COMPANYSIGNIN_SUCCESS';
export const COMPANY_SIGNOUT = 'COMPANY_SIGNOUT';
export const COMPANY_GETPROFILE = 'COMPANY_GETPROFILE';
export const COMPANY_EDITPROFILE = 'COMPANY_EDITPROFILE';
export const COMPANY_PROFILEERROR = 'COMPANY_PROFILEERROR';
export const COMPANY_GETREVIEWS = 'COMPANY_GETREVIEWS';
export const COMPANY_GETREVIEW = 'COMPANY_GETREVIEW';
export const COMPANY_REVIEWS_ERROR = 'COMPANY_REVIEWS_ERROR';
export const COMPANY_CREATE_JOB = 'COMPANY_CREATE_JOB';
export const COMPANY_GETALLJOBS = 'COMPANY_GETALLJOBS';
export const COMPANY_GETJOB = 'COMPANY_GETJOB';
export const COMPANY_JOBERROR = 'COMPANY_JOBERROR';
export const MARK_FAVORITE_SUCCESS = 'MARK_FAVORITE_SUCCESS';
export const MARK_FEATURED_SUCCESS = 'MARK_FEATURED_SUCCESS';
export const IMAGE_ERROR = 'IMAGE_ERROR';
export const POST_IMAGE = 'POST_IMAGE';
export const REPLY_MESSAGE = 'REPLY_MESSAGE';
export const UPDATE_APPLICANTSTATUS = 'UPDATE_APPLICANTSTATUS';

// Student Authorization
export const STUDENT_SIGNUP_SUCCESS = 'STUDENT_SIGNUP_SUCCESS';
export const STUDENT_SIGNUP_FAIL = 'STUDENT_SIGNUP_FAIL';
export const STUDENT_USER_LOADED = 'STUDENT_USER_LOADED';
export const STUDENT_AUTH_ERROR = 'STUDENT_AUTH_ERROR';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Student
export const STUDENT_PROFILE_SUCCESS = 'STUDENT_PROFILE_SUCCESS';
export const STUDENT_PROFILE_FAIL = 'STUDENT_PROFILE_FAIL';
export const STUDENT_COUNT_SUCCESS = 'STUDENT_COUNT_SUCCESS';
export const STUDENT_COUNT_FAIL = 'STUDENT_COUNT_FAIL';

// Student - Update job preference
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL';

// Student - Company Search
export const COMPANY_SEARCH_SUCCESS = 'COMPANY_SEARCH_SUCCESS';
export const COMPANY_SEARCH_FAIL = 'COMPANY_SEARCH_FAIL';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

//Student- Jobs
export const STUDENT_APPLY_JOB = 'STUDENT_APPLY_JOB';
export const STUDENT_GETALLJOBS = 'STUDENT_GETALLJOBS';
export const STUDENT_JOB_DETAILS = 'STUDENT_JOB_DETAILS';
export const STUDENT_JOBERROR = 'STUDENT_JOBERROR';

//Student applications

// Admin actions
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const ADMIN_USER_LOADED = 'ADMIN_USER_LOADED';
export const COMPANY_AVERAGE_RATING = 'COMPANY_AVERAGE_RATING';
export const MOST_REVIEWED_COMPANY = 'MOST_REVIEWED_COMPANY';
export const TOP_STUDENT_REVIEWERS = 'TOP_STUDENT_REVIEWERS';
export const TOP_CEO = 'TOP_CEO';
export const MOST_VIEWED_COMPANY = 'MOST_VIEWED_COMPANY';
export const REVIEW_PER_DAY = 'REVIEW_PER_DAY';
export const REVIEW_PER_DAY_ERROR = 'REVIEW_PER_DAY_ERROR';
export const COMPANY_AVERAGE_RATING_ERROR = 'COMPANY_AVERAGE_RATING_ERROR';
export const MOST_REVIEWED_COMPANY_ERROR = 'MOST_REVIEWED_COMPANY_ERROR';
export const TOP_STUDENT_REVIEWERS_ERROR = 'TOP_STUDENT_REVIEWERS_ERROR';
export const TOP_CEO_ERROR = 'TOP_CEO_ERROR';
export const MOST_VIEWED_COMPANY_ERROR = 'MOST_VIEWED_COMPANY_ERROR';
export const REVIEWS_GET = 'REVIEWS_GET';
export const REVIEWS_GET_ERROR = 'REVIEWS_GET_ERROR';
export const POST_APPROVAL = 'POST_APPROVAL';
export const POST_APPROVAL_ERROR = 'POST_APPROVAL';

export const COMPANY_LIST_GET = 'COMPANY_LIST_GET';
export const ADMIN_COMPANY_REVIEWS_GET = 'ADMIN_COMPANY_REVIEWS_GET';
export const COMPANY_HIRED_APPLICANTS_GET = 'COMPANY_HIRED_APPLICANTS_GET';
export const COMPANY_APPLICANT_DEMOGRAPHICS_GET =
    'COMPANY_APPLICANT_DEMOGRAPHICS_GET';
export const COMPANY_LIST_GET_ERROR = 'COMPANY_LIST_GET_ERROR';
export const ADMIN_COMPANY_REVIEWS_GET_ERROR =
    'ADMIN_COMPANY_REVIEWS_GET_ERROR';
export const COMPANY_HIRED_APPLICANTS_GET_ERROR =
    'COMPANY_HIRED_APPLICANTS_GET_ERROR';
export const COMPANY_APPLICANT_DEMOGRAPHICS_GET_ERROR =
    'COMPANY_APPLICANT_DEMOGRAPHICS_GET_ERROR';

export const PHOTO_SUCCESS = 'PHOTO_SUCCESS';
export const PHOTO_ERROR = 'PHOTO_ERROR';